platform :ios, '8.0'
pod 'DTCoreText', '~> 1.6.11'
pod 'AFNetworking', '1.3.3'
pod 'CocoaLumberjack', '~> 1.7.0'
pod 'VKFoundation', '0.1.1'
pod 'CocoaHTTPServer'

target 'videoplayer2Tests' do
  pod 'Specta',      '~> 0.2.1'
  pod 'Expecta',     '~> 0.3.0'
  pod 'OCMock',      '~> 2.2.1'
  pod 'CocoaHTTPServer'
end
